# Generated by Django 5.1.2 on 2024-10-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=220)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=200)),
                ('episodes', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(upload_to='anime_cover_image')),
                ('documents', models.FileField(upload_to='anime_documents')),
                ('status', models.CharField(choices=[('aired', 'aired'), ('notaired', 'notaired')], max_length=300)),
                ('category', models.ManyToManyField(to='animesugoi.category')),
            ],
        ),
    ]
